import Head from 'next/head'
import Image from 'next/image'
import { TopBar } from '@/components/TopBar'
import { Header } from '@/components/Header'
import { Container } from '@chakra-ui/react'
import { ProductCard } from '@/components/ProductCard'

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <main>
        <Container size={{lg: 'lg'}}>
          <Header />
        </Container>

        <Container size={{lg: 'lg'}}>
          <ProductCard />
        </Container>
      </main>
    </>
  )
}
